feat: change generator to 7.9.0

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -5,18 +5,24 @@ name: Swift
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
 
 jobs:
   build:
-
     runs-on: macos-latest
 
     steps:
-    - uses: actions/checkout@v4
-    - name: Build
-      run: swift build -v
+      - uses: actions/checkout@v4
+      - name: Build
+        run: |
+          swift build -v
+          # for debugging:
+          # set -o pipefail
+          # output=$(swift build -v 2>&1) || {
+          #   echo "$output" | grep -i "error\|failed\|fatal" >&2
+          #   exit 1
+          # }
     #- name: Run tests
     #  run: swift test -v
